<a href="https://colab.research.google.com/github/endlessrunnrer/pratice-Python/blob/main/numpy%EC%8B%A4%EC%8A%B5%E3%85%87.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Array**

**Numpy**
는 수학 연산과 배열 처리를 쉽게 만들어주는 필수 도구입니다.

왜 NumPy를 사용할까?

빠름: 일반 파이썬보다 수학 계산이 훨씬 빠릅니다.

배열(Array) 처리: 수많은 데이터를 한 번에 다룰 때 유용합니다. (리스트보다 강력함)

수학 함수 제공: 행렬, 통계, 삼각함수 등 다양한 수학 기능을 지원합니다.

데이터 분석과 과학 계산에 필수: 머신러닝, 데이터 과학에서 기본 도구로 사용됩니다.






In [ ]:
import numpy as np

a = np.array([1, 2, 3])
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])
a[0]=333
print(a)

b= np.array(([1,2,3], [4,556,56]))
print(b.shape)
print(b[0,0], b[0,2], b[1,2])

<class 'numpy.ndarray'>
(3,)
1 2 3
[333   2   3]
(2, 3)
1 3 56


주의! 리스트나 numpy나 시작하는 행이나 열은 항상 0부터이다.


---


예시: list a = [3, 4, 5]

a[0] = 3

a[1] = 4

a[2] = 5

이런 식으로 말이다. 시작은 0부터이다.

In [ ]:
import numpy as np

a = np.zeros((2, 2))  # 2x2 배열에 모든 요소가 0인 배열 생성
print(a)
# [[0. 0.]
#  [0. 0.]]

b = np.ones((1, 2))  # 1x2 배열에 모든 요소가 1인 배열 생성
print(b)
# [[1. 1.]]

c = np.full((2, 2), 7)  # 2x2 배열에 모든 요소가 7인 배열 생성
print(c)
# [[7 7]
#  [7 7]]

d = np.eye(2)  # 2x2 단위행렬(identity matrix) 생성
print(d)
# [[1. 0.]
#  [0. 1.]]

e = np.random.random((2, 2))  # 2x2 배열에 0~1 사이의 랜덤 값을 가진 배열 생성
print(e)
# [[0.12345678 0.23456789]  # (랜덤 값이므로 실행할 때마다 값이 다를 수 있음)
#  [0.34567890 0.45678901]]


[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.68219791 0.0274997 ]
 [0.40528795 0.97514699]]


In [ ]:
import numpy as np

a = np.array(([1, 2, 3, 4], [5, 6, 7, 8], [243, 45646, 43312, 111]))
# a는 3x4 크기의 배열로, 값은 다음과 같음:
# [[    1     2     3     4]
#  [    5     6     7     8]
#  [  243 45646 43312   111]]

# ????????????????????????
b = a[:2, 1:3]  # a 배열의 일부분(슬라이싱)을 가져와 b에 저장
# 슬라이싱: a의 첫 두 행(0, 1번 행)과 1~2번 열을 선택
# b는 아래와 같은 배열:
# [[2 3]
#  [6 7]]
#????????????????????????

print(a[0, 1])  # a 배열의 0번 행, 1번 열 값을 출력
# 출력: 2

b[0, 0] = 77  # b의 0번 행, 0번 열 값을 77로 변경
# 여기서 중요한 점! b는 a의 **일부분을 참조**한 배열이기 때문에,
# b의 값을 바꾸면 a도 함께 바뀐다!

print(a[0, 1])  # 다시 a 배열의 0번 행, 1번 열 값을 출력
# 출력: 77 (b에서 값을 바꿨기 때문에 a의 값도 77로 바뀜)


2
77


b = a[:2, 1:3] 부분 쉽게 설명
슬라이싱의 의미


a[:2, 1:3]:
행 범위: :2 → 0번 행부터 1번 행까지 선택

열 범위: 1:3 → 1번 열부터 2번 열까지 선택

따라서 2x2 부분 배열을 선택하게 돼.

b는 원래 배열 a의 복사본이 아닌 참조


**b는 a의 일부를 가리키는 포인터(참조)**야.
그래서 b의 값을 바꾸면 a도 함께 바뀌는 거지.


In [ ]:
import numpy as np
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

row_1 = a[1, :]  # 1번 행의 모든 열을 선택 (1차원 배열로 반환)
row_2 = a[1:2, :]  # 1번 행을 선택하되, 2차원 형태 유지
print(row_1, row_1.shape)
# 출력: [5 6 7 8] (4,)
print(row_2, row_2.shape)
# 출력: [[5 6 7 8]] (1, 4)

col_1 = a[:, 1]  # 모든 행에서 1번 열을 선택 (1차원 배열로 반환)
col_2 = a[:, 1:2]  # 모든 행에서 1번 열을 선택하되, 2차원 형태 유지
print(col_1, col_1.shape)
# 출력: [ 2  6 10] (3,)
print(col_2, col_2.shape)
# 출력: [[ 2]
#         [ 6]
#         [10]] (3, 1)


[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


1.    row_1 vs row_2

row_1 = a[1, :] → 1차원 배열 (shape: (4,))

1번 행을 1차원 배열로 가져옴.

결과: [5 6 7 8]

row_2 = a[1:2, :] → 2차원 배열 (shape: (1, 4))

1번 행을 2차원 배열로 유지. (행이 1개뿐인 2차원 배열)
결과: [[5 6 7 8]]

2. col_1 vs col_2

col_1 = a[:, 1] → 1차원 배열 (shape: (3,))

모든 행의 1번 열을 1차원 배열로 가져옴.

결과: [ 2 6 10]

col_2 = a[:, 1:2] → 2차원 배열 (shape: (3, 1))

모든 행의 1번 열을 2차원 배열로 유지.


??????????????????????????

이해가 안감... 아니 이게 어째서 1차원하고 2차원 차이로 갈리는 거지?


둘 다 값은 같아 보이지만...

row_1 = a[1, :]

1차원 배열로 반환되며, 리스트처럼 동작함.

모양(shape): (4,) → 요소가 4개인 1줄짜리 배열

행(row) 개념이 없음 (단순한 값들의 나열)

row_2 = a[1:2, :]

2차원 배열로 반환되며, 행과 열이 명확하게 나눠져 있음.

모양(shape): (1, 4) → 1행 4열인 2차원 배열

In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6]])

print(a[[0, 1, 2], [0, 1, 0]])
# 출력: [1 4 5]
# 👉 Fancy Indexing: 각각 (0, 0), (1, 1), (2, 0) 위치의 요소를 선택하여 배열로 반환
# a[0, 0] = 1, a[1, 1] = 4, a[2, 0] = 5

print(np.array([a[0, 0], a[1, 1], a[2, 0]]))
# 출력: [1 4 5]
# 👉 일반 배열 생성: 직접 각 요소를 선택해 1차원 배열 생성
# np.array([1, 4, 5])와 동일


# ??????????????????????????????????
print(a[a[0, 0], [1, 1]])
# 출력: [3 3]
# 👉 a[0, 0]의 값은 1, 따라서 a[1, [1, 1]]과 동일하게 동작
# a[1, 1] = 3이므로 3이 두 번 반환됨

print(np.array([a[0, 1], a[0, 1]]))
# 출력: [2 2]
# 👉 직접 같은 값을 두 번 선택해 배열 생성
# np.array([2, 2])와 동일
#??????????????????????????????????????


[1 4 5]
[1 4 5]
[4 4]
[2 2]


우웩.. 아 머리아파. 이거 뭐야? print(a[a[0, 0], [1, 1]])

왜 결과가 [4,4]임???

print(a[1, [1,1])이 되는데? 이걸 어케 계산함?

행과 행렬이라고 치면, 결과값이 a[1, 3]아닌가??  [1,1]을 먼저 계산하면? 이거 좌표잖아.


2️⃣ a[1, [1, 1]]는 무슨 의미일까?


a[1, [1, 1]]는 Fancy Indexing으로 작동해.

여기서 (1번 행에서 1번 열)을 두 번 선택한다는 의미야. (존나 중요)::::::::::::

즉, 1번 행의 1번 열 값은 4니까, 이 값을 두 번 반복해서 반환해.

따라서 **[4, 4]**가 출력되는 거야!

그저 G.O.A.T 역시 챗지퓌티!

내가 보기엔 a[1, [1,1]]의 핵심은 맨 처음의 1이 횟수이고 0으로시작하니까 2번임.

뒤에 것이 [1,1]이니까 그대로 계산하면 4이다.

 근데 이것을 두번 반환하니까 결과는 [4,4]


In [ ]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

print(a)
# 출력:
# [[ 1  2  3]
#  [ 4  5  6]
#  [ 7  8  9]
#  [10 11 12]]

b = np.array([0, 2, 0, 1])

print(a[np.arange(4), b])
# 출력: [ 1  6  7 11 ]
# Fancy Indexing: (0,0), (1,2), (2,0), (3,1)의 값을 선택

a[np.arange(4), b] += 10

print(a)
# 출력:
# [[11  2  3]
#  [ 4  5 16]
#  [17  8  9]
#  [10 21 12]]


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


오늘은 여기까지~~~ / 2025.02.12  